CREATE DATABASE IF NOT EXISTS ssis;

USE ssis;

CREATE TABLE IF NOT EXISTS college(
    id VARCHAR(10) NOT NULL UNIQUE PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS course(
    id VARCHAR(15) NOT NULL UNIQUE PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    college VARCHAR(10) DEFAULT NULL,

    FOREIGN KEY (college) REFERENCES college(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS student(
    id VARCHAR(9) NOT NULL UNIQUE PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    course VARCHAR(15) DEFAULT NULL,
    year TINYINT UNSIGNED NOT NULL CHECK (year BETWEEN 1 AND 5),
    gender ENUM('male', 'female', 'other'),

    FOREIGN KEY (course) REFERENCES course(id) ON DELETE SET NULL ON UPDATE CASCADE
);