from os import getenv

SECRET_KEY = getenv('SECRET_KEY')
DB_PORT = getenv('DB_PORT')
DB_NAME = getenv("DB_NAME")
DB_USERNAME = getenv("DB_USERNAME")
DB_PASSWORD = getenv("DB_PASSWORD")
DB_HOST = getenv("DB_HOST")

LOCAL_SECRET_KEY = getenv('LOCAL_SECRET_KEY')
LOCAL_DB_PORT = getenv('LOCAL_DB_PORT')
LOCAL_DB_NAME = getenv("LOCAL_DB_NAME")
LOCAL_DB_USERNAME = getenv("LOCAL_DB_USERNAME")
LOCAL_DB_PASSWORD = getenv("LOCAL_DB_PASSWORD")
LOCAL_DB_HOST = getenv("LOCAL_DB_HOST")

CLOUDINARY_CLOUD_NAME = getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = getenv('CLOUDINARY_API_SECRET')